### ISSUE TITLE
nothing forward to unomaly

### ISSUE THREAD

**Issue by dio99** [unomaly/graylog-plugin-unomaly#10]
plugin installed on graylog 3.0 launched and no error
but i dont see anyting forward to unomaly

**Comment by andskli** [comment]
Hi @dio99 

A few questions to be able to help you properly.

First and most importantly, are you using the shipped self-signed certificate on the Unomaly instance? If yes, is it properly installed in the java CA store on the graylog instance(s)?

Are you seeing any POST requests to the batch endpoint in `/var/log/apache2/access.log` on the Unomaly instance?

Are you seeing indications in the top bar of graylog indicating that messages are not only coming in, but also being forwarded?

**Comment by dio99** [comment]
nope did not import any cert since i did not know that.. just added the plugin and tried to send to unomaly..  yes im using the self signed by default install unomaly..
i checked now and i see lots off cert error java..

Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:397)
        at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:302)
        at sun.security.validator.Validator.validate(Validator.java:253)
        at sun.security.ssl.X509T

**Comment by andskli** [comment]
So you have a few options then;

1. Install a real certificate on the Unomaly instance
2. Import the self signed certificate from the Unomaly instance to the java truststore.
3. (least prefered) switch over communications to plain text HTTP in the graylog plugin configuration, edit `/etc/apache2/sites-enabled/unomaly.conf`, remove the line containing `RewriteRule ^/?(.*) https://%{SERVER_NAME}/$1 [R,L]` and restart apache on the Unomaly machine.

As this issue is not directly related to the plugin itself, but rather to the way Java handles certificates, I will close this issue for now with the recommendation above.

**Comment by dio99** [comment]
i just doing this for test purpose so i go for option to not use https, i guess this will affect the gui access to but thats no big issues now in test..

**Comment by andskli** [comment]
GUI access will still be available like before. The only difference is that it will not force the redirect to https

**Comment by dio99** [comment]
yep saw that in conf.. works now to get logs
